#ifndef DEF_H
#define DEF_H


#include "main.h"

#define StatusH     HAL_GPIO_WritePin(Status_GPIO_Port, Status_Pin, GPIO_PIN_RESET)
#define StatusL     HAL_GPIO_WritePin(Status_GPIO_Port, Status_Pin, GPIO_PIN_SET)

#define DI0      HAL_GPIO_ReadPin(DI0_GPIO_Port, DI0_Pin)
#define DI1      HAL_GPIO_ReadPin(DI1_GPIO_Port, DI1_Pin)
#define DI2      HAL_GPIO_ReadPin(DI2_GPIO_Port, DI2_Pin)
#define DI3      HAL_GPIO_ReadPin(DI3_GPIO_Port, DI3_Pin)
#define DI4      HAL_GPIO_ReadPin(DI4_GPIO_Port, DI4_Pin)
#define DI5      HAL_GPIO_ReadPin(DI5_GPIO_Port, DI5_Pin)
#define DI6      HAL_GPIO_ReadPin(DI6_GPIO_Port, DI6_Pin)
#define DI7      HAL_GPIO_ReadPin(DI7_GPIO_Port, DI7_Pin)
#define DI8      HAL_GPIO_ReadPin(DI8_GPIO_Port, DI8_Pin)
#define DI9      HAL_GPIO_ReadPin(DI9_GPIO_Port, DI9_Pin)
#define DI10     HAL_GPIO_ReadPin(DI10_GPIO_Port, DI10_Pin)
#define DI11     HAL_GPIO_ReadPin(DI11_GPIO_Port, DI11_Pin)
#define DI12     HAL_GPIO_ReadPin(DI12_GPIO_Port, DI12_Pin)
#define DI13     HAL_GPIO_ReadPin(DI13_GPIO_Port, DI13_Pin)

#define DQ0      HAL_GPIO_ReadPin(DQ0_GPIO_Port, DQ0_Pin)
#define DQ1      HAL_GPIO_ReadPin(DQ1_GPIO_Port, DQ1_Pin)
#define DQ2      HAL_GPIO_ReadPin(DQ2_GPIO_Port, DQ2_Pin)
#define DQ3      HAL_GPIO_ReadPin(DQ3_GPIO_Port, DQ3_Pin)
#define DQ4      HAL_GPIO_ReadPin(DQ4_GPIO_Port, DQ4_Pin)
#define DQ5      HAL_GPIO_ReadPin(DQ5_GPIO_Port, DQ5_Pin)
#define DQ6      HAL_GPIO_ReadPin(DQ6_GPIO_Port, DQ6_Pin)
#define DQ7      HAL_GPIO_ReadPin(DQ7_GPIO_Port, DQ7_Pin)
#define DQ8      HAL_GPIO_ReadPin(DQ8_GPIO_Port, DQ8_Pin)
#define DQ9      HAL_GPIO_ReadPin(DQ9_GPIO_Port, DQ9_Pin)
#define DQ10     HAL_GPIO_ReadPin(DQ10_GPIO_Port, DQ10_Pin)
#define DQ11     HAL_GPIO_ReadPin(DQ11_GPIO_Port, DQ11_Pin)
#define DQ12     HAL_GPIO_ReadPin(DQ12_GPIO_Port, DQ12_Pin)
#define DQ13     HAL_GPIO_ReadPin(DQ13_GPIO_Port, DQ13_Pin)

#define DQ0L     HAL_GPIO_WritePin(DQ0_GPIO_Port, DQ0_Pin, GPIO_PIN_RESET)
#define DQ0H     HAL_GPIO_WritePin(DQ0_GPIO_Port, DQ0_Pin, GPIO_PIN_SET)
#define DQ1L     HAL_GPIO_WritePin(DQ1_GPIO_Port, DQ1_Pin, GPIO_PIN_RESET)
#define DQ1H     HAL_GPIO_WritePin(DQ1_GPIO_Port, DQ1_Pin, GPIO_PIN_SET)
#define DQ2L     HAL_GPIO_WritePin(DQ2_GPIO_Port, DQ2_Pin, GPIO_PIN_RESET)
#define DQ2H     HAL_GPIO_WritePin(DQ2_GPIO_Port, DQ2_Pin, GPIO_PIN_SET)
#define DQ3L     HAL_GPIO_WritePin(DQ3_GPIO_Port, DQ3_Pin, GPIO_PIN_RESET)
#define DQ3H     HAL_GPIO_WritePin(DQ3_GPIO_Port, DQ3_Pin, GPIO_PIN_SET)
#define DQ4L     HAL_GPIO_WritePin(DQ4_GPIO_Port, DQ4_Pin, GPIO_PIN_RESET)
#define DQ4H     HAL_GPIO_WritePin(DQ4_GPIO_Port, DQ4_Pin, GPIO_PIN_SET)
#define DQ5L     HAL_GPIO_WritePin(DQ5_GPIO_Port, DQ5_Pin, GPIO_PIN_RESET)
#define DQ5H     HAL_GPIO_WritePin(DQ5_GPIO_Port, DQ5_Pin, GPIO_PIN_SET)
#define DQ6L     HAL_GPIO_WritePin(DQ6_GPIO_Port, DQ6_Pin, GPIO_PIN_RESET)
#define DQ6H     HAL_GPIO_WritePin(DQ6_GPIO_Port, DQ6_Pin, GPIO_PIN_SET)
#define DQ7L     HAL_GPIO_WritePin(DQ7_GPIO_Port, DQ7_Pin, GPIO_PIN_RESET)
#define DQ7H     HAL_GPIO_WritePin(DQ7_GPIO_Port, DQ7_Pin, GPIO_PIN_SET)
#define DQ8L     HAL_GPIO_WritePin(DQ8_GPIO_Port, DQ8_Pin, GPIO_PIN_RESET)
#define DQ8H     HAL_GPIO_WritePin(DQ8_GPIO_Port, DQ8_Pin, GPIO_PIN_SET)
#define DQ9L     HAL_GPIO_WritePin(DQ9_GPIO_Port, DQ9_Pin, GPIO_PIN_RESET)
#define DQ9H     HAL_GPIO_WritePin(DQ9_GPIO_Port, DQ9_Pin, GPIO_PIN_SET)
#define DQ10L     HAL_GPIO_WritePin(DQ10_GPIO_Port, DQ10_Pin, GPIO_PIN_RESET)
#define DQ10H     HAL_GPIO_WritePin(DQ10_GPIO_Port, DQ10_Pin, GPIO_PIN_SET)
#define DQ11L     HAL_GPIO_WritePin(DQ11_GPIO_Port, DQ11_Pin, GPIO_PIN_RESET)
#define DQ11H     HAL_GPIO_WritePin(DQ11_GPIO_Port, DQ11_Pin, GPIO_PIN_SET)
#define DQ12L     HAL_GPIO_WritePin(DQ12_GPIO_Port, DQ12_Pin, GPIO_PIN_RESET)
#define DQ12H     HAL_GPIO_WritePin(DQ12_GPIO_Port, DQ12_Pin, GPIO_PIN_SET)
#define DQ13L     HAL_GPIO_WritePin(DQ13_GPIO_Port, DQ13_Pin, GPIO_PIN_RESET)
#define DQ13H     HAL_GPIO_WritePin(DQ13_GPIO_Port, DQ13_Pin, GPIO_PIN_SET)

#endif  //DEF_H
