set(BUILD_VERSION_FILE "${CMAKE_CURRENT_LIST_DIR}/BuildVersion.txt")
set(BUILD_VERSION_HEADER_FILE "${CMAKE_CURRENT_LIST_DIR}/inc/BuildNumber.hpp")

IF(EXISTS ${BUILD_VERSION_FILE})
    file(READ ${BUILD_VERSION_FILE} BUILD_VERSION_VALUE)
    math(EXPR BUILD_VERSION_VALUE "${BUILD_VERSION_VALUE}+1")
ELSE()
    set(BUILD_VERSION_VALUE "1")
ENDIF()

file(WRITE ${BUILD_VERSION_FILE} "${BUILD_VERSION_VALUE}")
file(WRITE ${BUILD_VERSION_HEADER_FILE}
"#pragma once

#define BUILD_NUMBER ${BUILD_VERSION_VALUE}
")
